services:
  db:
    image: postgres:17.0
    container_name: db
    env_file:
      - .env
    networks:
      - transcendence
    volumes:
      - db:/var/lib/postgresql/data
    restart: always
  web:
    depends_on:
      - db
    build: ./transcendence
    container_name: web
    networks:
      - transcendence
    volumes:
      - ./transcendence:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always

networks:
  transcendence:
    driver: bridge

volumes:
  db:
