services:
  db:
    image: postgres:17.0
    container_name: db
    env_file:
      - .env
    networks:
      - transcendence
    volumes:
      - db:/var/lib/postgresql/data
    restart: always

  web:
    depends_on:
      - db
    build: ./transcendence
    container_name: web
    networks:
      - transcendence
    volumes:
      - ./transcendence:/app
      - ./transcendence/pong/static:/app/pong/static
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always

  nginx:
    depends_on:
      - web
    container_name: nginx
    build: ./nginx
    ports:
      - "10000:443"
      - "8080:80"
    volumes:
      - ./transcendence/pong/static:/usr/src/app/static
    networks:
      - transcendence
    restart: always

networks:
  transcendence:
    driver: bridge

volumes:
  db:


