# Generated by Django 5.1.2 on 2024-11-06 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0002_user_games_played_user_losses_user_wins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='user',
        ),
    ]
