# Generated by Django 5.1.2 on 2024-11-11 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0004_chat_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='message',
            new_name='content',
        ),
    ]
