# Generated by Django 5.1.3 on 2024-11-24 18:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0006_alter_chat_options_rename_user_chat_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banned_users',
            field=models.ManyToManyField(related_name='banned_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
